### ISSUE TITLE
[Enhancement] Improve Bibliogram redirection from Nitter

### ISSUE THREAD

**Issue by lazytownfan** [PussTheCat-org/PussTheCat.org#3]
Scenario: I visit `@twitterUser` on this Nitter instance at `nitter.pussthecat.org/u/twitterUser`, who inputs their Instagram account `@igUser` as their website, and their Instagram URL is rendered as `bibliogram.pussthecat.org/igUser`.

Issue: If I visit the Instagram link (redirected to this Bibliogram instance), then `bibliogram.pussthecat.org/igUser` strictly leads to a 404 Not Found page. Luckily, Bibliogram automatically asks if I really wanted to go to `bibliogram.pussthecat.org/u/igUser`.

Fix: If possible, eplace redirecting from `instagram.com/igUser` to `bibliogram.pussthecat.org/u/igUser` as the destination, instead of `bibliogram.pussthecat.org/igUser`.

**Comment by TheFrenchGhosty** [comment]
Bibliogram is using /u/ on purpose, if I try to rewrite the URL it will break stuff, feel free to ask cadence to have Bibliogram itself supporting it though.

I can't do anything on my end.
