### ISSUE TITLE
ProxiTok subdomain get Fatal error on search tiktok by username

### ISSUE THREAD

**Issue by bugbounted** [PussTheCat-org/PussTheCat.org#6]
Hi [PussTheCat.org](https://github.com/PussTheCat-org),
your subdomain for ProxiTok service is on Fatal error for search by username :
https://proxitok.pussthecat.org/@bianca2849
please fix it 
finest regards

**Comment by TheFrenchGhosty** [comment]
Reported upsteam: https://github.com/pablouser1/ProxiTok/issues/45

Next time things break I'm killing my instance.
